### ISSUE TITLE
Roadmap: 宣伝用ポスターの作成

### ISSUE THREAD

**Issue by ykmtsd** [KU-eSports/KUeST-PR#3]
## 製作に取り掛かる前に決めること
- [x] [ポスターのサイズ](https://github.com/KU-eSports/KUeST-PR/issues/4)
- [ ] [ポスターの内容](https://github.com/KU-eSports/KUeST-PR/issues/5)
- [ ] [ポスターのデザイン]()
- [x] [製作期日](https://github.com/KU-eSports/KUeST-PR/issues/6)

## 製作完了までに決めること
- [x] [予算](https://github.com/KU-eSports/KUeST-PR/issues/7)
- [ ] [印刷枚数](https://github.com/KU-eSports/KUeST-PR/issues/8)
- [x] [印刷方法](https://github.com/KU-eSports/KUeST-PR/issues/9)

**Comment by N4K4eight** [comment]
ポスターのサイズは、A4縦型にしようと思っています。
内容は、部員求の文言、Twitter、discordです。
期日は、出来ればスプラカスタムまでに仕上げて貼りたいです。なので、内容にスプラカスタムのことを入れることも考えています。

印刷方法は、学校のプリンターを使おうと思います。枚数は、総合教育棟の各掲示板に1枚です。数えてきます💦
予算はぼくのポケットマネーからだすので、死なない程度に()

**Comment by ykmtsd** [comment]
![08674B6D-58F3-467D-957A-8232D50A6047](https://user-images.githubusercontent.com/109290606/196322055-a214924a-30df-4e3f-8f99-2c168175d554.png)

**Comment by ykmtsd** [comment]
おしまいです

**Comment by Tooooomo** [comment]
![sad](https://user-images.githubusercontent.com/104683109/196330764-91bae1ca-c6d7-474a-a44c-3caec7fc747f.gif)

**Comment by N4K4eight** [comment]
え？カガライブって公認なんですか！？！？

**Comment by ykmtsd** [comment]
ポスターを貼ることができるのは**原則**公認団体なので、カガライブは何かの理由で例外扱いされてる説

**Comment by ykmtsd** [comment]
公認取れるように頑張ろう！
ということで、ポスター制作は一旦休止します
公認が取れたら再開しましょう
